# Generated by Django 4.1.4 on 2023-06-04 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ваше Ф.И.О.')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('child_full_name', models.CharField(max_length=50, verbose_name='Ф.И.О. ребёнка')),
            ],
            options={
                'verbose_name': 'Адаптационная заявка',
                'verbose_name_plural': 'Адаптационные заявки',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ваше Ф.И.О.')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('text', models.TextField(verbose_name='Что Вас интересует:')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ваше Ф.И.О.')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('education', models.CharField(choices=[('ОО', 'Основное общее'), ('СО', 'Среднее общее'), ('СП', 'Среднее проф.'), ('В', 'Высшее')], max_length=3, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
                ('specialization', models.CharField(choices=[('В', 'Воспитатель'), ('ПВ', 'Помощник воспитателя'), ('ПДО', 'Педагог доп. образования'), ('С', 'Спец'), ('Д', 'Другое')], max_length=3, verbose_name='Специальность')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Заявка на трудоустройство',
                'verbose_name_plural': 'Заявки на трудоустройство',
            },
        ),
        migrations.CreateModel(
            name='ChildApplication',
            fields=[
                ('adaptiveapplication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='application.adaptiveapplication')),
                ('age', models.IntegerField(verbose_name='Возраст ребёнка')),
                ('art_club', models.BooleanField(verbose_name='Юный художник (Рисование)')),
                ('dance_club', models.BooleanField(verbose_name='Танцуем вместе (Танцы)')),
                ('music', models.BooleanField(verbose_name='Весёлые нотки (Музыкальный кружок)')),
                ('physical_culture_club', models.BooleanField(verbose_name='Спортивные ребята (Физкультурный кружок)')),
                ('needlework_club', models.BooleanField(verbose_name='Волшебные ручки (Рукоделие)')),
                ('robotics', models.BooleanField(verbose_name='Ротоботехника')),
                ('foreign_languages', models.BooleanField(verbose_name='Английский язык')),
                ('orientation_of_education', models.CharField(choices=[('OBJ', 'Основы безопасности жизнедеятельности'), ('NPV', 'Нравствено-патриотическое воспитание'), ('KET', 'Культурно-этические нормы'), ('VFK', 'Воспитание финансовой культуры'), ('EV', 'Экологическое воспитание'), ('IR', 'Индивидуальное развитие'), ('RR', 'Развитие речи'), ('MO', 'Методика общения'), ('HER', 'Художествено-эстетическое развитие'), ('MRV', 'Музыкально-ритмическое воспитание'), ('FV', 'Физическое воспитание'), ('RKRT', 'Развитие конструирования и ручного труда')], max_length=4, verbose_name='Направленость обучения')),
                ('specialist_service', models.CharField(choices=[('LD', 'Логопед-дефектолог'), ('S', 'Сурдопедагог (Нарушение слуха)'), ('T', 'Тифлопедагог (Нарушение зрения)')], max_length=4, verbose_name='Услуги специалиста')),
            ],
            options={
                'verbose_name': 'Заявка на посесещение садика',
                'verbose_name_plural': 'Заявки на посесещения садика',
            },
            bases=('application.adaptiveapplication',),
        ),
    ]
