# Generated by Django 4.1.4 on 2023-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_w'),
    ]

    operations = [
        migrations.AlterField(
            model_name='w',
            name='full_name',
            field=models.IntegerField(verbose_name='Ваше Ф.И.О.'),
        ),
    ]
