# Generated by Django 4.1.4 on 2023-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_childapplication_teacherapplication_delete_w_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childapplication',
            options={'verbose_name': 'Заявка на посесещение садика', 'verbose_name_plural': 'Заявки на посесещения садика'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='teacherapplication',
            options={'verbose_name': 'Заявка на трудоустройство', 'verbose_name_plural': 'Заявки на трудоустройство'},
        ),
    ]
