# Generated by Django 4.1.4 on 2023-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_childapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Что Вас интересует:'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='education',
            field=models.CharField(choices=[('ОО', 'Основное общее'), ('СО', 'Среднее общее'), ('СП', 'Среднее проф.'), ('В', 'Высшее')], max_length=3, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='experience',
            field=models.IntegerField(verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='teacherapplication',
            name='specialization',
            field=models.CharField(choices=[('В', 'Воспитатель'), ('ПВ', 'Помощник воспитателя'), ('ПДО', 'Педагог доп. образования'), ('С', 'Спец'), ('Д', 'Другое')], max_length=3, verbose_name='Специальность'),
        ),
    ]
