# Generated by Django 4.1.4 on 2023-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplication',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
    ]
