# Generated by Django 4.1.4 on 2023-06-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О.')),
                ('specialization', models.CharField(choices=[('В', 'Воспитатель'), ('ПВ', 'Помощник воспитателя'), ('ПДО', 'Педагог доп. образования'), ('С', 'Спец'), ('Д', 'Другое')], max_length=3, verbose_name='Специальность')),
                ('education', models.CharField(choices=[('ОО', 'Основное общее'), ('СО', 'Среднее общее'), ('СП', 'Среднее проф.'), ('В', 'Высшее')], max_length=3, verbose_name='Образование')),
                ('experience', models.IntegerField(verbose_name='Стаж работы')),
                ('quote', models.CharField(max_length=100, verbose_name='Цитата')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Подагог',
                'verbose_name_plural': 'Подагоги',
            },
        ),
    ]
