# Generated by Django 4.1.4 on 2023-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(choices=[('Основное общее', 'Основное общее'), ('Среднее общее', 'Среднее общее'), ('Среднее проф.', 'Среднее проф.'), ('Высшее', 'Высшее')], max_length=50, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(choices=[('Воспитатель', 'Воспитатель'), ('Помощник воспитателя', 'Помощник воспитателя'), ('Педагог доп. образования', 'Педагог доп. образования'), ('Спец', 'Спец')], max_length=50, verbose_name='Специальность'),
        ),
    ]
