# Generated by Django 4.1.4 on 2023-06-04 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О. ребёнка')),
                ('bdd', models.DateField(verbose_name='Дата рождения')),
                ('parent_full_name', models.CharField(max_length=50, verbose_name='Ф.И.О. родителя(ей)')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона родителя/опекуна')),
                ('age', models.IntegerField(verbose_name='Возраст ребёнка')),
                ('art_club', models.BooleanField(verbose_name='Юный художник (Рисование)')),
                ('dance_club', models.BooleanField(verbose_name='Танцуем вместе (Танцы)')),
                ('music', models.BooleanField(verbose_name='Весёлые нотки (Музыкальный кружок)')),
                ('physical_culture_club', models.BooleanField(verbose_name='Спортивные ребята (Физкультурный кружок)')),
                ('needlework_club', models.BooleanField(verbose_name='Волшебные ручки (Рукоделие)')),
                ('robotics', models.BooleanField(verbose_name='Ротоботехника')),
                ('foreign_languages', models.BooleanField(verbose_name='Английский язык')),
                ('orientation_of_education', models.CharField(choices=[('OBJ', 'Основы безопасности жизнедеятельности'), ('NPV', 'Нравствено-патриотическое воспитание'), ('KET', 'Культурно-этические нормы'), ('VFK', 'Воспитание финансовой культуры'), ('EV', 'Экологическое воспитание'), ('IR', 'Индивидуальное развитие'), ('RR', 'Развитие речи'), ('MO', 'Методика общения'), ('HER', 'Художествено-эстетическое развитие'), ('MRV', 'Музыкально-ритмическое воспитание'), ('FV', 'Физическое воспитание'), ('RKRT', 'Развитие конструирования и ручного труда')], max_length=4, verbose_name='Направленость обучения')),
                ('specialist_service', models.CharField(choices=[('LD', 'Логопед-дефектолог'), ('S', 'Сурдопедагог (Нарушение слуха)'), ('T', 'Тифлопедагог (Нарушение зрения)')], max_length=4, verbose_name='Услуги специалиста')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
