# Generated by Django 4.1.4 on 2023-05-30 15:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название программы')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Ф.И.О.')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона родителя/опекуна')),
                ('needs_a_psychologist', models.BooleanField(verbose_name='Нуждается в психологе')),
                ('needs_a_logopedist', models.BooleanField(verbose_name='Нуждается в логопеде')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.program', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
